### ISSUE TITLE
didnt run

### ISSUE THREAD

**Issue by 1ak31sha** [MattSurabian/DuckHunt-JS#69]
tried 2 versions of npm. didnt see any .nvmrc file. what version of node do you use?
got these 2 errors

1)
```
❯ npm start

> DuckHunt-JS@3.1.0 start
> webpack-dev-server

(node:43467) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)
[hardsource:6f323ef8] Writing new cache 6f323ef8...
node:events:490
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (node:net:1774:16)
    at listenInCluster (node:net:1822:12)
    at GetAddrInfoReqWrap.doListen [as callback] (node:net:1971:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1801:8)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}

Node.js v19.8.1
```

2)
```
DuckHunt-JS on  master [!] is 📦 v3.1.0 via  v14.21.3 via 💠 default took 3s
❯ npm start

> DuckHunt-JS@3.1.0 start /Users/lakeisha/workspace/DuckHunt-JS
> webpack-dev-server

events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use 127.0.0.1:8080
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1516:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:73:8)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1358:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -48,
  syscall: 'listen',
  address: '127.0.0.1',
  port: 8080
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! DuckHunt-JS@3.1.0 start: `webpack-dev-server`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the DuckHunt-JS@3.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/lakeisha/.npm/_logs/2024-05-12T23_55_25_736Z-debug.log
```

**Comment by MattSurabian** [comment]
It has been quite a while since I've run this locally so the depreciation warning isn't surprising to me. I'll try to get the deps updated soon.

However, the error that is causing you problems is a standard "address in use" issue. Something else on your machine is already using port 8080. To correct that shut down the other process, or change the configuration in this project to use an alternate port that is available on your machine.

**Comment by MattSurabian** [comment]
This is the line to change for updating the port https://github.com/MattSurabian/DuckHunt-JS/blob/master/webpack.config.js#L47
